[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about/index.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact/index.html"
  status = 200

[[redirects]]
  from = "/games"
  to = "/games/index.html"
  status = 200

[[redirects]]
  from = "/pricing"
  to = "/pricing/index.html"
  status = 200

[[redirects]]
  from = "/pricing2"
  to = "/pricing2/index.html"
  status = 200

[[redirects]]
  from = "/pricing3"
  to = "/pricing3/index.html"
  status = 200

[[redirects]]
  from = "/news"
  to = "/news/index.html"
  status = 200

[[redirects]]
  from = "/faq"
  to = "/faq/index.html"
  status = 200

[[redirects]]
  from = "/location"
  to = "/location/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login/index.html"
  status = 200

[[redirects]]
  from = "/register"
  to = "/register/index.html"
  status = 200

[[redirects]]
  from = "/knowledgebase"
  to = "/knowledgebase/index.html"
  status = 200

[[redirects]]
  from = "/affliate"
  to = "/affliate/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 